import { createSlice } from "@reduxjs/toolkit";

/**
 * The statistical values that are computable are listed here as
 * an "enum"
 */
const STATISTICAL_VALUES = {
    mean: "mean",
    median: "median",
    derivative: "derivative",
    percentile: "percentile",
}

const STATISTICAL_VALUES_LIST = Object.values(STATISTICAL_VALUES);



const MODEL_DATA_TEMPLATE = {   // single model
    color: null,                // if not set it defaults to standard value from api
    isVisible: true,            // show/hide individual models from a group
    mean: true,
    derivative: true,
    median: true,
    percentile: true,
}

const MODEL_GROUP_TEMPLATE = { 
    name: null,
    modelList: [],
    models: {},         // models is lookup table
    isVisible: true,    // show/hide complete group
    visibileSV: {       // lookup table so the reducer impl. can be more convenient
        mean: true,
        derivative: true,
        median: true,
        percentile: true,
    }
}

/**
 * The initial state of the modelSlice defines the data structure in the 
 * store. Each plot has its own data i.e. have separate model(groups).
 * 
 * IF you change this initial state you have to adapt the first test in the
 * corresponding test file, that tests the initial state.
 */
const initialState = {
    modelGroupList: ["all"],
    // currently active plot
    modelGroups: {
        // this objects holds key-value-pairs, the keys being the model-group 
        // identifier and the values being the settings for each group 
        "all": { 
            // model group storing all information until it is possible 
            // to implement more model groups
            name: "All OCTS models",
            modelList: ["CCMI-1_ACCESS_ACCESS-CCM-refC2"],
            models: { // models is lookup table
                "CCMI-1_ACCESS_ACCESS-CCM-refC2": { // single model
                    color: null, // if not set it defaults to standard value from api
                    isVisible: true, // show/hide individual models from a group
                    mean: true,
                    derivative: true,
                    median: true,
                    percentile: true,
                }
            },
            isVisible: false, // show/hide complete group
            visibileSV: { // lookup table so the reducer impl. can be more convenient
                mean: true,
                derivative: true,
                median: true,
                percentile: true,
            }
        }
    },
}

/**
 * The modelSlice is generated by the redux toolkit. The reducers are defined here
 * and the corresponding actions are auto-generated.
 */
const modelsSlice = createSlice({
    name: "models",
    initialState,
    reducers: {

        /**
         * This reducer accepts an action object returned from setModelGroup()
         * 
         *      e.g. dispatch(setModelGroup({
         *              groupId: "refC2", 
         *              modelList: ["CCMI-1_ACCESS_ACCESS-CCM-refC2", "CCMI-1_CCCma_CMAM-refC2"]
         *      }))
         * 
         * and calculates the new state based on the action and the action 
         * data given in action.payload.
         * 
         * This method provides a convenient interface for the AddModelGroupModal
         * by allowing to dispatch a groupId with the required models. If
         * the group already exists the corresponding data is updated otherwise
         * the reducer takes care of creating a group.
         * 
         * @param {object} state the current store state of: state/plot
         * @param {object} action accepts the action returned from updateModelGroup()
         * @param {object} action.payload the payload is an object containg the given data
         * @param {string} action.payload.groupId the name of the group to set
         * @param {string} action.payload.modelList the list of models the group should have
         */
        setModelGroup(state, action) { 
            const { groupId, modelList } = action.payload;
            // set model group
            if (state.modelGroupList.includes(groupId)) {
                const selectedModelGroup = state.modelGroups[groupId];
                // remove unwanted
                const toDelete = selectedModelGroup.filter(model => !modelList.includes(model));
                toDelete.forEach(
                    model => delete selectedModelGroup[model]
                );
                // add new ones
                for (let model of modelList) {
                    if (!selectedModelGroup[model]){ // initialize with default settings
                        selectedModelGroup.modelList.push(model);
                        selectedModelGroup.models[model] = Object.assign({}, MODEL_DATA_TEMPLATE);
                    }
                };
            } else { // create new group
                state.modelList.push(groupId);
                state.modelGroups[groupId] = Object.assign({}, MODEL_GROUP_TEMPLATE);
                const currentGroup = state.modelGroups[groupId];
                for (let model of modelList) {
                    currentGroup.modelList.push(model);
                    currentGroup.models[model] = Object.assign({}, MODEL_DATA_TEMPLATE);
                }
            }
        }, 

        /**
         * This reducer accepts an action object returned from setVisibility()
         *       e.g. dispatch(setVisibility(
         *          {groupID: "all", modelID: "CCMI-1_ACCESS_ACCESS-CCM-refC2", isVisible: false}
         *       ))
         * and calculates the new state based on the action and the action 
         * data given in action.payload.
         * 
         * In this case the visibility of a given model in the given group is set
         * to the new value.
         * 
         * @param {object} state the current store state of: state/plot
         * @param {object} action accepts the action returned from updateModelGroup()
         * @param {object} action.payload the payload is an object containg the given data
         * @param {string} action.payload.groupID a string specifying the group of the target model
         * @param {string} action.payload.modelID a string specifying the target model
         * @param {boolean} action.payload.isVisible is the model visible as boolean
         */
        setVisibility(state, action) { 
            const { groupID, modelID, isVisible } = action.payload;
            const activeSettings = state.settings[state.plotId];
            const activeModel = activeSettings[groupID].models[modelID];
            if (activeModel === undefined) {
                throw `tried to access model with modelID "${modelID}" that is not yet defined!`;
            } 
            activeModel.isVisible = isVisible;
        },

        /**
         * This reducer accepts an action object returned from setStatisticalValuesIncluded()
         *      e.g. dispatch(setVisibility(
         *          {groupID: "all", modelID: "CCMI-1_ACCESS_ACCESS-CCM-refC2", svType: "mean", isIncluded: true}
         *       ))
         * and calculates the new state based on the action and the action 
         * data given in action.payload.
         * 
         * In this case for a given model is set whether it should be included
         * in the calculation of the given statistical value (SV).
         * 
         * @param {object} state the current store state of: state/plot
         * @param {object} action accepts the action returned from updateModelGroup()
         * @param {object} action.payload the payload is an object containg the given data
         * @param {string} action.payload.groupID a string specifying the group of the target model
         * @param {string} action.payload.modelID a string specifying the target model
         * @param {string} action.payload.svType the SV as a string
         * @param {boolean} action.payload.isIncluded should the model be included for the given SV
         */
        setStatisticalValueIncluded(state, action) { // this is for an individual model
            // svType has to be a string of the form: 
            // mean | derivative | median | percentile
            const { groupID, modelID, svType, isIncluded } = action.payload;
            const activeSettings = state.settings[state.plotId];
            const activeModel = activeSettings[groupID].models[modelID];
            if (activeModel === undefined) {
                throw `tried to access model with modelID "${modelID}" that is not yet defined!`;
            }
            if (!STATISTICAL_VALUES_LIST.includes(svType)) { // svType doesn't represent a valid statistical value
                throw `tried to set statistial value "${svType}" that is not a valid statistical value (${STATISTICAL_VALUES_LIST.join("|")})`;
            }
            activeModel[svType] = isIncluded;
        },

        /**
         * This reducer accepts an action object returned from setStatisticalValueForGroup()
         *      e.g. dispatch(setStatisticalValueForGroup(
         *          {groupID: "all", svType: STATISTICAL_VALUES.median, isIncluded: true}
         *      ));
         * and calculates the new state based on the action and the action 
         * data given in action.payload.
         * 
         * In this case for a given group is set whether the given statistical values (SV)
         * should be displayed.
         * 
         * @param {object} state the current store state of: state/plot
         * @param {object} action accepts the action returned from updateModelGroup()
         * @param {object} action.payload the payload is an object containg the given data
         * @param {string} action.payload.groupId a string specifying the group
         * @param {string} action.payload.svType the SV as a string
         * @param {boolean} action.payload.isIncluded should the SV be displayed for the given group
         */
        setStatisticalValueForGroup(state, action) { // this is for an entire group
            const { groupId, svType, isIncluded } = action.payload;
            
            if (!STATISTICAL_VALUES_LIST.includes(svType)) { // svType doesn't represent a valid statistical value
                throw `tried to set statistial value "${svType}" that is not a valid statistical value (${STATISTICAL_VALUES_LIST.join("|")})`;
            }
            if (!state.modelGroupList.includes(groupId)) { // no group with this name in store
                throw `tried to access "${groupId}" which is not a valid group`;
            };

            state.modelGroups[groupId].visibileSV[svType] = isIncluded;
        },

        /**
         * This reducer accepts an action object returned from setVisibilityForGroup()
         *      e.g. dispatch(setVisibilityForGroup(
         *          {groupID: "refC2", isVisibile: true}
         *      ));
         * and calculates the new state based on the action and the action 
         * data given in action.payload.
         * 
         * In this case for a given group is set whether it should be visibile or not.
         * 
         * @param {object} state the current store state of: state/plot
         * @param {object} action accepts the action returned from updateModelGroup()
         * @param {object} action.payload the payload is an object containg the given data
         * @param {string} action.payload.groupId a string specifying the group
         * @param {string} action.payload.svType the SV as a string
         * @param {boolean} action.payload.isIncluded should the SV be displayed for the given group
         */
        setVisibilityForGroup(state, action) { // this is for an entire group
            const { groupId, isVisible } = action.payload;

            if (!state.modelGroupList.includes(groupId)) {
                throw `tried to access "${groupId}" which is not a valid group`;
            };

            state.modelGroups[groupId].isVisible = isVisible;
        },
    }
})

/**
 * The here listed actions are exported and serve as an interface for
 * the view (our react components).
 */
export const { 
    addModels,
    removeModels,
    updatedModelGroup,
    addedModelGroup,
    setVisibility, 
    setStatisticalValueIncluded, 
    setStatisticalValueForGroup
} = modelsSlice.actions;

/**
 * The reducer combining all reducers defined in the plot slice. 
 * This has to be included in the redux store, otherwise dispatching 
 * the above defined actions wouldn't trigger state updates.
 */
export default modelsSlice.reducer;

/**
 * This function is a selector, i.e. it allows components to 
 * select only a specific piece of data from the store. In this
 * case an object holding all current model groups is returned.
 * 
 * @param {object} state the global redux state
 * @returns {object} an object holding all current model groups
 */
export const selectCurrentModelGroups = state => state.models[state.plot.plotId];
/**
 * This selectors allows components to select the a specific model group
 * from the store for the current active plot.
 * 
 * @param {object} state the global redux state
 * @param {string} groupId a string specifying what model group shall be returned
 * @returns {object} the model group with the given id
 */
export const selectCurrentModelGroup = (state, groupId) => state.models[state.plot.plotId][groupId];