/* tslint:disable */
/* eslint-disable */
/**
 * Swagger REST API for O3as
 * This is **O3as REST API** based on the OpenAPI specification and leveraging Swagger UI for the [Ozone assessment service](https://o3as.data.kit.edu).  For the detailed documentation, please, visit [O3as documention](https://o3as.readthedocs.io).  **By using our service you agree to the [Terms of Use](https://o3as.data.kit.edu/policies/terms-of-use.html)** 
 *
 * The version of the OpenAPI document: 0.8.4
 * Contact: o3as-support@lists.kit.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

