config:
  project_repos: {}
  credentials:
    - id: o3as-dockerhub-vykozlov
      username_var: JPL_DOCKERUSER
      password_var: JPL_DOCKERPASS
environment:
  JPL_DOCKERPUSH: "o3webapp"
  JPL_DOCKERFORCEBUILD: enabled
#  JPL_IGNOREFAILURES: enabled
  JPL_KEEPGOING: enabled # need to comment out, if stop on failure is expected
  LANG: C.UTF-8
sqa_criteria:
  QC.Sty:
    repos:
      this_repo:
        commands:
        - sh -c "yarn install --frozen-lockfile && ./node_modules/.bin/eslint src/ -f checkstyle -o eslint-codestyle.xml"
        container: processing
  QC.Uni:
    repos:
      this_repo:
        commands:
        - sh -c "npm run test -- --coverage --watchAll=false ."
        container: processing
  QC.Sec:
    repos:
      this_repo:
        commands:
        - sh -c "yarn audit --groups dependencies --level=high"
        container: processing
  QC.Doc:
    repos:
      this_repo:
        commands:
        - sh -c "patch ./node_modules/better-docs/bundler.js < ./better-docs-bundler.patch && npm run docs"
        container: processing

timeout: 600
