config:
  credentials: []
  project_repos: {}
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: disabled
sqa_criteria:
  QC.Sty:
    repos:
      this_repo:
        commands:
        - sh -c "npm ci --audit=false && ./node_modules/.bin/eslint src/ -f checkstyle -o eslint-codestyle.xml"
        container: processing
  QC.Uni:
    repos:
      this_repo:
        commands:
        - sh -c "npm run test -- --coverage --watchAll=false ."
        container: processing
  QC.Sec:
    repos:
      this_repo:
        commands:
        - sh -c "npm config set production=true && npm audit --audit-level=high"
        container: processing
  QC.Doc:
    repos:
      this_repo:
        commands:
        - sh -c "patch ./node_modules/better-docs/bundler.js < ./better-docs-bundler.patch && npm run docs"
        container: processing

timeout: 600
