services:
  processing:
    command: sleep 6000000
    image: node:16.13-alpine
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
