services:
  processing:
    command: sleep 6000000
    image: node:16.13
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build

  o3webapp:
     build:
        context: "."
        dockerfile: "./Dockerfile"
        args:
          target: ${O3WEBAPP_DOCKER_TARGET}
     image: "o3as/o3webapp:${O3WEBAPP_DOCKER_TAG}"

version: '3.7'
